### PR TITLE
Issue#11: View to delete or edit a referral

### PR DESCRIPTION
**Pull request by pprolancer**

### CODE REVIEW

**Comment by vincentdavis** [comment]
@pedro-walter can you please review and merge if it look good.

**Comment by pedro-walter** [comment]
Was the intention to delete a Referring Entity (previously Physician) or to delete a Patient Visit (previously Referral)? Currently, the code deletes the first.

**Comment by vincentdavis** [comment]
@pprolancer @pedro-walter  This is to edit or delete a record d visit. Change/edit the treating physician, count, referring entity.

**Comment by pprolancer** [comment]
@vincentdavis
I misunderstood regarding "referral". then I though you meant "Referring Entity".
@pedro-walter 
I will change the codes and will pull request again.

**Comment by pprolancer** [comment]
@vincentdavis and @pedro-walter 
I have changed the codes to could edit/delete a patient visit.
please take a look at that and merge if that is OK.
Thanks

**Pull request merged**
