### PR TITLE
issue #83 completed and renamed as issue #83A

### PR DESCRIPTION
**Pull request by kushaw**
expand/collapse menu issue: done
pagination is not working: done
clear the layouts folder: done
clear the Dashboard page: done
Remove Profiles and keep only Myprofile and Logout btn: done
organization Edit update the DB also: done;
Data front end validations: done

### CODE REVIEW

**Comment by pprolancer** [comment]
Hi @kushaw 
regarding pagination, I dont see any pagination in organization.
please let me know what is wrong?
Thanks

**Comment by kushaw** [comment]
The pagination is added and updated in the same issue#83A

**Comment by pprolancer** [comment]
Hi @kushaw 
as I explained in skype: """
your pagination implementation is not correct

you implemented pagination locally.

indeed we need to do pagination remotely

if you call /api/v1/organization/ you will have 2 field in json data:

1- result

2- pagination

in pagination we have pagination info. something like this:

{
 'count': 45,
 'current_page': 1,
 'first_page': 1,
 'last_page': 5,
 'next_page': 2,
 'next_url': 'http://localhost:8000/api/v1/organization?page=2',
 'page_size': 10,
 'previous_page': null,
 'previous_url': null
}

maybe next_url and previous_url be un-used

but you should use other info to create your pagination buttons link in your table

count = total records

current_page = current page number

first_page = first page number

last_page = last page number

page_size = max size of every page

then you should use this data to create your pagination buttons in UI and bind click events for buttons according this info

FYI, to load data of page number N you should add a parameter called page in end of url: something like this:

http://localhost:8000/api/v1/organization?page=1

http://localhost:8000/api/v1/organization?page=2

...

http://localhost:8000/api/v1/organization?page=N

does this make sense?

then to clear more, you should create pagination buttons according your pagination result of /api/v1/pagination/ api dynamically

Thanks

"""

**Comment by kushaw** [comment]
As we are using the latest technology and tools I recommend to leverage the capabilities of the same

As initially when the page is loading we are loading all the data related to organization and as all the pagination stuff can be handled by front-end JavaScript  recommend the Js approach

I believe that if we use the above said approach it will increase the unnecessary ajax call to the server however the same can be achieved by using JS datatable.
only things we need to take from the database are:

'current_page': 1,
 'page_size': 10,

all other functionalities can be achieved by JS in frontend
Please let me know your comments

**Pull request merged**
