### PR TITLE
"closes #82" : created new branch as branch 82 was giving problem in push/pull requests

### LINKED ISSUE #82: design and implement base structure of ui
as you know we want to implement new ui2 by angularjs.
ui should be designed by a metronic theme: http://www.keenthemes.com/preview/metronic/theme/admin_2_angularjs/

@kushaw, please let me know if any question.

### PR DESCRIPTION
**Pull request by kushaw**
"closes #82"

### CODE REVIEW

**Comment by pprolancer** [comment]
@kusha
you should consider 2 thing:
1- requirements.txt should not be in your commit. I see this is changed.
2- I see a lot files in assets exists while we dont need them. then please remove all not required files from assets.

Thanks

**Comment by kusha** [comment]
Hi guys! @pprolancer just misspelled your name, @kushaw . Wish you a progress with your project! Bye.

**Comment by pprolancer** [comment]
@kushaw 
another thing:
3 - I see the static file and I dont see previous structure in that directory. as I mentioned, you shouldn't change other folders in static. you need just to change ui2.
I see you removed css, fonts and js subdirs in static folder.
as I told my suggestion is to do your steps from scratch.
thanks

**Comment by kushaw** [comment]
all the above said changes are done in issue#83A hence we can close this

**Pull request closed without merging**
