### PR TITLE
Issue#83 closed

### PR DESCRIPTION
**Pull request by kushaw**
Issue#83 is closed. please pull.

### CODE REVIEW

**Comment by pprolancer** [comment]
@kushaw 
Thanks for your codes.
I have checked the codes. I see we have lots of plugins and pages in the source codes which we dont need them.
then please polish the codes and remove everything which is not required. for example all not required plugins, css, js, html, images and icons, ... should be removed from entire of directory ui2.
please make your change in this current branch issue#83 and pull your commits again.
Thanks

**Comment by kushaw** [comment]
I understand that however as the application is in development stage and we may require more plugins later in the application hence i have not removed the JS and related CSS of the plugin. I thought we will remove all those once the application is ready with all the page.

Do you still want me to remove it ? please let me know.

**Comment by vincentdavis** [comment]
It is better to not track them with git (they can be in your
filesystem) and git add .. them as needed.

On Friday, April 15, 2016, kushaw <notifications@github.com> wrote:

> I understand that however as the application is in development stage and
> we may require more plugins later in the application hence i have not
> removed the JS and related CSS of the plugin. I thought we will remove all
> those once the application is ready with all the page.
>
> Do you still want me to remove it ? please let me know.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Heteroskedastic/Dr-referral-tracker/pull/105#issuecomment-210586666>
>


-- 
Sent from mobile app.
Vincent Davis
720-301-3003

**Comment by pprolancer** [comment]
@kushaw 
yes, that is better to remove all not required files.
Thanks

**Comment by kushaw** [comment]
I removed all the extra plugins and files.

**Pull request closed without merging**
